apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yelb-ingress
  namespace: yelb
  labels:
    app: yelb
spec:
  rules:
  - host: "yelb.k8s.vmwdxb.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: yelb-ui
            port:
              number: 80
