apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: yelb
  name: yelb-ingress
spec:
  rules:
  - host: "yelb.k8s.vmwdxb.com"
    http:
      paths:
      - path: 
        backend:
          serviceName: yelb-ui
          servicePort: 80
